version: '3.8'

services:
  database:
    container_name: '${PROJECT_ABBREVIATION}_db'
    image: '${DB_TYPE}:${DB_VERSION}'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db-volume:/var/lib/mysql

  php:
    container_name: '${PROJECT_ABBREVIATION}_php'
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    environment:
      DATABASE_URL: '${DB_TYPE}://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}?serverVersion=${DB_VERSION}'
    volumes:
      - ./:/var/www/symfony_docker
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  nginx:
    container_name: '${PROJECT_ABBREVIATION}_nginx'
    image: nginx:stable-alpine
    ports:
      - '${WEBSERVER_PORT}:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./.docker/nginx/development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  db-volume:
